-- 5) 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력하는 SQL문
-- 대여 금액 = 30일 대여 금액 - (할인율 * 30일 대여금액) -> INT
SELECT DISTINCT(C.CAR_ID), C.CAR_TYPE, ROUND(DAILY_FEE * 30 - (DAILY_FEE * 30 * (DISCOUNT_RATE/100))) AS FEE

FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE

--  1) 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중에서
WHERE C.CAR_TYPE IN ('세단', 'SUV')

-- 2) 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능한 자동차들 추출
AND C.CAR_ID NOT IN (
                        SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
                        OR END_DATE BETWEEN '2022-11-01' AND '2022-11-30'
                        OR (START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-30'))

AND DURATION_TYPE = '30일 이상'

-- 3) 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
AND ROUND(DAILY_FEE * 30 - (DAILY_FEE * 30 * (DISCOUNT_RATE/100))) BETWEEN 500000 AND 2000000

-- 4) 정렬
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC